<a href="https://colab.research.google.com/github/OmarMachuca851/Task/blob/main/Matrix_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Implementation of matrix product***

# ***Calculate matrix product manually***

### Given A and B

$$
A = \begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix}, \quad
B = \begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}
$$

### Lets calculate the matrix product **C = A x B**
#### Compute Each Element in **C**
Weĺl calculate each element using the formula and given steps.
* Combine each row of matrix A with each column of matrix **B**.
* Multiply the corresponding elements and take the sum of all combinations.
* Through multiplication and addition of the elements, each element of matrix C is

**Row1 C[0, * ]**

```ruby
C[0,0] = (-1x0) + (2x0) +(3x2) = 0 + 0 + 6 = 6
C[0,1] = (-1x2) + (2x2) +(3x9) = -2 + 4 + 27 = 29
C[0,2] = (-1x2) + (2x-8) +(3x-1) = -1 - 16 - 3 = -20
```

**Row2 C[1, * ]**

```python
C[0,0] = (4x0) + (-5x0) +(6x2) = 0 + 0 + 12 = 12
C[0,1] = (4x2) + (-5x2) +(6x9) = 8 - 10 + 54 = 52
C[0,2] = (4x1) + (-5x-8) +(6x-1) = 4 + 40 - 6 = 38
```

**Row1 C[2, * ]**

```c++
C[0,0] = (7x0) + (8x0) +(-9x2) = 0 + 0 - 18 = -18
C[0,1] = (7x2) + (8x2) +(-9x9) = 14 + 16 - 81 = -51
C[0,2] = (7x1) + (8x-8) +(-9x-1) = 7 - 64 + 9 = -48
```

### Final Matrix result **C**
$$
C = \begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{bmatrix} \quad
$$

## ***Problem 2: Calculating matrix products using numpy***

In [7]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

result1 = np.matmul(a_ndarray, b_ndarray)
print(f'Result using np.matmul(): \n{result1}')

result2 = np.dot(a_ndarray, b_ndarray)
print(f'\nREsult using np.dot():\n{result2}')

result3 = a_ndarray @ b_ndarray
print(f'\nResult using @ operator:\n{result3}')

Result using np.matmul(): 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

REsult using np.dot():
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

Result using @ operator:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## ***Problem 3: Implementation of calculation of a certain element***

In [8]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#calculate the (0,0) element of the result matrix
element_0_0 = 0
for k in range(3):
    element_0_0 += a_ndarray[0, k] * b_ndarray[k, 0]

print(f'The (0,0) element the result matrix is: {element_0_0}')

The (0,0) element the result matrix is: 6


## ***Problem 4: Implement matrix multiplication function***

In [9]:
def matrix_multiply(a, b):
    # get dimendions of the matrices
    a_rows, a_cols  = a.shape
    b_rows, b_cols = b.shape

    #check if matrices can be multiplied
    if a_cols != b_rows:
        raise ValueError('incompatible')

    #initialize result matrix
    result = np.zeros((a_rows, b_cols))

    #calcuate each element of the result matrix
    for i in range(a_rows):
        for j in range(b_cols):
            for k in range(a_cols):
                result[i, j] += a[i, k] * b[k, j]

    return result
# compute product
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

result = matrix_multiply(a_ndarray, b_ndarray)
print(f'Result of matrix multiplication: \n{result}')

Result of matrix multiplication: 
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## ***Problem 5: Judge the input whose calculation is not defined***

In [10]:
def matrix_multiply(a, b):
    # get dimendions of the matrices
    a_rows, a_cols  = a.shape
    b_rows, b_cols = b.shape

    #check if matrices can be multiplied
    if a_cols != b_rows:
        print('Error: Matrix multiplication no defined.')
        print(f'Matrix A has shape ({a_rows}, {a_cols}) and matrix B has shape ({b_rows}, {b_cols}).')
        print(f'For matrix multiplication  to be defined, the number of columns in A({a_cols}) must equal the number of rows in B ({b_rows}).')
        return None

    #initialize result matrix
    result = np.zeros((a_rows, b_cols))

    #calcuate each element of the result matrix
    for i in range(a_rows):
        for j in range(b_cols):
            for k in range(a_cols):
                result[i, j] += a[i, k] * b[k, j]

    return result

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[0, 2, 1], [0, 2, -8]])

result = matrix_multiply(d_ndarray, e_ndarray)
print(f'Result of matrix multiplication: \n{result}')

Error: Matrix multiplication no defined.
Matrix A has shape (2, 3) and matrix B has shape (2, 3).
For matrix multiplication  to be defined, the number of columns in A(3) must equal the number of rows in B (2).
Result of matrix multiplication: 
None


## ***Problem 6: Transposition***

In [11]:
# matrices with undefined matrix products
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(f'D shape: {d_ndarray.shape}')
print(f'E shape: {e_ndarray.shape}')

result = matrix_multiply(d_ndarray, e_ndarray)
print(f'Result:\n{result}')

#transpose E to make multiplication possible
e_ndarray_transposed = e_ndarray.T
print(f'D sahpe: {d_ndarray.shape}')
print(f'Transposed E sahpe: \n{e_ndarray_transposed.shape}')

result = matrix_multiply(d_ndarray, e_ndarray_transposed)
print(f"Result:\n{result}")

D shape: (2, 3)
E shape: (2, 3)
Error: Matrix multiplication no defined.
Matrix A has shape (2, 3) and matrix B has shape (2, 3).
For matrix multiplication  to be defined, the number of columns in A(3) must equal the number of rows in B (2).
Result:
None
D sahpe: (2, 3)
Transposed E sahpe: 
(3, 2)
Result:
[[ 46.  -4.]
 [-34.  73.]]
